export default {
  all: [{
    'id': 572,
    'text': 'Afghanistan'
  }, {
    'id': 133,
    'text': 'Albania'
  }, {
    'id': 457,
    'text': 'Algeria'
  }, {
    'id': 1535,
    'text': 'Argentina'
  }, {
    'id': 1541,
    'text': 'Armenia'
  }, {
    'id': 1591,
    'text': 'Australia'
  }, {
    'id': 1592,
    'text': 'Austria'
  }, {
    'id': 539,
    'text': 'Azerbaijan'
  }, {
    'id': 518,
    'text': 'Bahrain'
  }, {
    'id': 2010,
    'text': 'Bangladesh'
  }, {
    'id': 30,
    'text': 'Barbados'
  }, {
    'id': 79,
    'text': 'Belarus'
  }, {
    'id': 1624,
    'text': 'Belgium'
  }, {
    'id': 459,
    'text': 'Benin'
  }, {
    'id': 2104,
    'text': 'Bhutan'
  }, {
    'id': 1593,
    'text': 'Bolivia'
  }, {
    'id': 1590,
    'text': 'Bosnia and Herzegovina'
  }, {
    'id': 1584,
    'text': 'Botswana'
  }, {
    'id': 1606,
    'text': 'Brazil'
  }, {
    'id': 1588,
    'text': 'Bulgaria'
  }, {
    'id': 180,
    'text': 'Burkina Faso'
  }, {
    'id': 29,
    'text': 'Cabo Verde'
  }, {
    'id': 305,
    'text': 'Cambodia'
  }, {
    'id': 1581,
    'text': 'Cameroon'
  }, {
    'id': 1554,
    'text': 'Canada'
  }, {
    'id': 1566,
    'text': 'Chile'
  }, {
    'id': 1613,
    'text': 'China, Mainland'
  }, {
    'id': 1551,
    'text': 'Colombia'
  }, {
    'id': 577,
    'text': 'Costa Rica'
  }, {
    'id': 1537,
    'text': "Cote D'Ivoire"
  }, {
    'id': 1595,
    'text': 'Croatia'
  }, {
    'id': 2107,
    'text': 'Cuba'
  }, {
    'id': 2109,
    'text': 'Cyprus'
  }, {
    'id': 1570,
    'text': 'Czech Republic'
  }, {
    'id': 1577,
    'text': 'Denmark'
  }, {
    'id': 1599,
    'text': 'Dominican Republic'
  }, {
    'id': 1567,
    'text': 'Ecuador'
  }, {
    'id': 1609,
    'text': 'Egypt'
  }, {
    'id': 1572,
    'text': 'El Salvador'
  }, {
    'id': 1565,
    'text': 'Estonia'
  }, {
    'id': 476,
    'text': 'Ethiopia'
  }, {
    'id': 1620,
    'text': 'Finland'
  }, {
    'id': 1597,
    'text': 'France'
  }, {
    'id': 499,
    'text': 'Gabon'
  }, {
    'id': 531,
    'text': 'Georgia'
  }, {
    'id': 1596,
    'text': 'Germany'
  }, {
    'id': 1568,
    'text': 'Ghana'
  }, {
    'id': 1555,
    'text': 'Greece'
  }, {
    'id': 1556,
    'text': 'Guatemala'
  }, {
    'id': 2108,
    'text': 'Honduras'
  }, {
    'id': 1594,
    'text': 'Hong Kong'
  }, {
    'id': 1549,
    'text': 'Hungary'
  }, {
    'id': 1550,
    'text': 'Iceland'
  }, {
    'id': 1585,
    'text': 'India'
  }, {
    'id': 1539,
    'text': 'Indonesia'
  }, {
    'id': 495,
    'text': 'Iran'
  }, {
    'id': 1540,
    'text': 'Ireland'
  }, {
    'id': 1542,
    'text': 'Italy'
  }, {
    'id': 1615,
    'text': 'Japan'
  }, {
    'id': 530,
    'text': 'Jordan'
  }, {
    'id': 494,
    'text': 'Kazakhstan'
  }, {
    'id': 1617,
    'text': 'Kenya'
  }, {
    'id': 1562,
    'text': 'Korea'
  }, {
    'id': 56,
    'text': 'Kuwait'
  }, {
    'id': 543,
    'text': 'Kyrgyzstan'
  }, {
    'id': 55,
    'text': 'Laos'
  }, {
    'id': 1579,
    'text': 'Latvia'
  }, {
    'id': 182,
    'text': 'Lebanon'
  }, {
    'id': 219,
    'text': 'Liberia'
  }, {
    'id': 2121,
    'text': 'Liechtenstein'
  }, {
    'id': 1580,
    'text': 'Lithuania'
  }, {
    'id': 1709,
    'text': 'Malawi'
  }, {
    'id': 1611,
    'text': 'Malaysia'
  }, {
    'id': 2105,
    'text': 'Maldives'
  }, {
    'id': 1612,
    'text': 'Malta'
  }, {
    'id': 489,
    'text': 'Mauritius'
  }, {
    'id': 1589,
    'text': 'Mexico'
  }, {
    'id': 536,
    'text': 'Moldova'
  }, {
    'id': 2103,
    'text': 'Monaco'
  }, {
    'id': 409,
    'text': 'Mongolia'
  }, {
    'id': 57,
    'text': 'Montenegro'
  }, {
    'id': 1552,
    'text': 'Morocco'
  }, {
    'id': 1574,
    'text': 'Mozambique'
  }, {
    'id': 4,
    'text': 'Myanmar'
  }, {
    'id': 78,
    'text': 'Namibia'
  }, {
    'id': 112,
    'text': 'Nepal'
  }, {
    'id': 1616,
    'text': 'New Zealand'
  }, {
    'id': 178,
    'text': 'Nicaragua'
  }, {
    'id': 2117,
    'text': 'Niger'
  }, {
    'id': 1578,
    'text': 'Nigeria'
  }, {
    'id': 1573,
    'text': 'Norway'
  }, {
    'id': 477,
    'text': 'Oman'
  }, {
    'id': 1603,
    'text': 'Pakistan'
  }, {
    'id': 1582,
    'text': 'Panama'
  }, {
    'id': 177,
    'text': 'Paraguay'
  }, {
    'id': 1553,
    'text': 'Peru'
  }, {
    'id': 1604,
    'text': 'Philippines'
  }, {
    'id': 1564,
    'text': 'Poland'
  }, {
    'id': 1544,
    'text': 'Portugal'
  }, {
    'id': 1538,
    'text': 'Puerto Rico'
  }, {
    'id': 529,
    'text': 'Qatar'
  }, {
    'id': 1548,
    'text': 'Republic of Macedonia'
  }, {
    'id': 1560,
    'text': 'Romania'
  }, {
    'id': 1618,
    'text': 'Russia'
  }, {
    'id': 506,
    'text': 'Rwanda'
  }, {
    'id': 2106,
    'text': 'Saudi Arabia'
  }, {
    'id': 1605,
    'text': 'Senegal'
  }, {
    'id': 1547,
    'text': 'Serbia'
  }, {
    'id': 1840,
    'text': 'Seychelles'
  }, {
    'id': 1575,
    'text': 'Singapore'
  }, {
    'id': 1536,
    'text': 'Slovakia'
  }, {
    'id': 1587,
    'text': 'Slovenia'
  }, {
    'id': 1545,
    'text': 'South Africa'
  }, {
    'id': 1619,
    'text': 'Spain'
  }, {
    'id': 1623,
    'text': 'Sri Lanka'
  }, {
    'id': 1601,
    'text': 'Sweden'
  }, {
    'id': 1558,
    'text': 'Switzerland'
  }, {
    'id': 1561,
    'text': 'Taiwan'
  }, {
    'id': 537,
    'text': 'Tajikistan'
  }, {
    'id': 567,
    'text': 'Tanzania'
  }, {
    'id': 1607,
    'text': 'Thailand'
  }, {
    'id': 1598,
    'text': 'The Netherlands'
  }, {
    'id': 1543,
    'text': 'Togo'
  }, {
    'id': 1559,
    'text': 'Tunisia'
  }, {
    'id': 1622,
    'text': 'Turkey'
  }, {
    'id': 1602,
    'text': 'Uganda'
  }, {
    'id': 1610,
    'text': 'Ukraine'
  }, {
    'id': 1625,
    'text': 'United Arab Emirates'
  }, {
    'id': 1563,
    'text': 'United Kingdom'
  }, {
    'id': 1621,
    'text': 'United States'
  }, {
    'id': 1614,
    'text': 'Uruguay'
  }, {
    'id': 2115,
    'text': 'Uzbekistan'
  }, {
    'id': 1557,
    'text': 'Venezuela'
  }, {
    'id': 504,
    'text': 'Vietnam'
  }, {
    'id': 2122,
    'text': 'Zambia'
  }]
}
